Shirt.create(name: "Cool Story Bro", url: 'https://www.wordans.ca/music-t-shirt-cool-story-bro-tell-it-again-t-shirt-682046')
Shirt.create(name: "DynamicPictureOfYesterdaysShirt", url: 'http://shirts.onion/287342873648273')
Shirt.create(name: "There's A Nap for That", url: 'http://www.bowanddrape.com/clothing/A+Nap+App+pun_isher/194_h_3953488924')
Shirt.create(name: "Careless Whisper", url: 'https://www.youtube.com/watch?v=GaoLU6zKaws')
Shirt.create(name: "DoobieBrothers", url: 'http://doobiebrothers.com')
Shirt.create(name: "I know HTML (How to meet ladies)", url: 'http://www.amazon.com/buXsbaum-T-Shirt-know-HTML-ladies/dp/B00BWSE91K')
Shirt.create(name: "Laser Cat T-Shirt", url: 'http://6dollarshirts.com/t-shirts/Laser-Cat-p-11434.html')
Shirt.create(name: "Macho Man Randy Savage - Be A Man", url: 'https://www.youtube.com/watch?v=dMbcOC5dS5k')
Shirt.create(name: "Montreal", url: 'https://youtu.be/dQw4w9WgXcQ')
Shirt.create(name: "Save Tyrion", url: 'https://www.etsy.com/transaction/205893967')
Shirt.create(name: "TardisExpress", url: 'http://example.com/tardisexpress')
Shirt.create(name: "teespring", url: 'http://teespring.com/')
Shirt.create(name:"Plain White Tee", url:'https://www.youtube.com/watch?v=EbJtYqBYCV8')
Tag.create(name: "Macabre")
Tag.create(name: "Groovy")
Tag.create(name: "dogespeak")
Tag.create(name: "funtime")
Tag.create(name: "plain white")
Tag.create(name: "Crop top")
Tag.create(name: "Sci-fi")
Tag.create(name: "Sports")
Tag.create(name: "beyonce")
Tag.create(name: "clubbing")
Tag.create(name: "die Scheiße")
Tag.create(name: "nunez")
Tag.create(name: "streets-ahead")
Tag.create(name:"Leggings")
Tag.create(name:"Punny")
Tag.create(name:"Tight")
